# Generated by Django 3.1.5 on 2021-01-26 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orientador',
            name='id',
        ),
        migrations.AlterField(
            model_name='anopublicacao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autor',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='documento',
            name='keys',
        ),
        migrations.AddField(
            model_name='documento',
            name='keys',
            field=models.ManyToManyField(to='core.PalavrasChave'),
        ),
        migrations.AlterField(
            model_name='orientador',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
